### ISSUE TITLE
jboss.jca.common.api.validator.ValidateException: IJ010075: The resource adapter metadata must contain either an outbound or inbound configuration

### ISSUE THREAD

**Issue by urbandroid** [datanucleus/datanucleus-jdo-jca#1]
Hello, i'm trying to deploy a jdo resource adapter to wildfly 10 with this code: https://github.com/urbandroid/datanucleus-jca-adapter 
java:/TestDS datasource deployed to server resource adapter must use this datasource.

I'm getting error below can you help me?

```
1:55:12,652 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-7) MSC000001: Failed to start service jboss.deployment.unit."datanucleus-jdo-jca-6.0.6.rar".INSTALL: org.jboss.msc.service.StartException in service jboss.deployment.unit."datanucleus-jdo-jca-6.0.6.rar".INSTALL: WFLYSRV0153: Failed to process phase INSTALL of deployment "datanucleus-jdo-jca-6.0.6.rar"
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:154)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: org.jboss.jca.common.api.validator.ValidateException: IJ010075: The resource adapter metadata must contain either an outbound or inbound configuration
	at org.jboss.as.connector.deployers.ra.processors.ParsedRaDeploymentProcessor.process(ParsedRaDeploymentProcessor.java:216)
	at org.jboss.as.connector.deployers.ra.processors.ParsedRaDeploymentProcessor.deploy(ParsedRaDeploymentProcessor.java:127)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	... 5 more
Caused by: org.jboss.jca.common.api.validator.ValidateException: IJ010075: The resource adapter metadata must contain either an outbound or inbound configuration
	at org.jboss.jca.common.metadata.spec.ResourceAdapterImpl.validate(ResourceAdapterImpl.java:228)
	at org.jboss.jca.common.metadata.spec.ConnectorImpl.validate(ConnectorImpl.java:350)
	at org.jboss.as.connector.deployers.ra.processors.ParsedRaDeploymentProcessor.process(ParsedRaDeploymentProcessor.java:187)
	... 7 more
```

**Comment by andyjefferson** [comment]
Use groups.io or Gitter for support, as per the website.
